@startuml
|→ Activity Diagram ←|

start
:서비스 시작;

repeat
  :수면의 질(시간) 측정;
  :기상 시간(07:00) 도달;
  :흰 알 깨기;
  
  if (설정된 취침 시간에 수면을 취했고\n핸드폰 사용이 감지되지 않았나요?) then (예)
    :점수 += 10 (점수 저장);
  else (아니요)
    :점수 += 0;
  endif
  
  :점수 기록;
  :활동(행동 변화, 점수 확인);
  :취침시간(22:00) 도달;
  :결산 타임 알림 전송;
  :결산 시작;
  
  if (에너지 점수 ≥ 80?) then (예)
    fork
      :특별한 반숙이 컬렉션 제공;
    fork again
      :일반 반숙이 컬렉션 제공;
    fork again
      :눌러붙은 반숙이 제공;
    end fork
  endif
  
  :새로운 흰 알 제공;
repeat while (서비스 지속)

stop
@enduml